### ISSUE TITLE
To Ben: Can you upload the code you used when you get the chance?

### ISSUE THREAD

**Issue by cansav09** [BernsteinLabMSUTeam/P1_02_DifferentialMethylation#1]
Thanks for answering all our questions and the work you've been doing. Please upload the code you used when you get the chance. I'd really like to know what was done to the data we have from you.

**Comment by biobenkj** [comment]
Yep, will definitely get this uploaded shortly.

**Comment by biobenkj** [comment]
@aibernstein @cansav09 @vanoevsa which branch are things being committed to? Master?

**Comment by aibernstein** [comment]
Master is fine. It's empty right now and the other branch isn't even valid (was when we were learning how to use GitHub!)

**Comment by biobenkj** [comment]
Incoming PR today. Will reference here.

**Comment by biobenkj** [comment]
PR submitted and requesting review from @aibernstein
